name: Jeff's MBP
username: jeff
password: password
mediator:
  host: localhost
  port: 7331
projects:
  Sample:
    location: ~/Documents/projects/sample
    ignore:
      - "*.pyc"
      - "/.git/*"
      - "/.DS_Store"
    shell: /bin/bash
    source:
      - $HOME/.bash_profile
    actions:
      - cat: cat sample.txt

  YACS:
    location: ~/Documents/projects/yacs
    ignore:
      - "*.pyc"
      - "*/.DS_Store"
      - "*/.git/*"
    shell: /bin/bash
    source:
      - $HOME/.bash_profile
    actions:
      test: workon yacs && make test

  Describe:
    location: ~/Documents/projects/describe
    ignore:
      - "*.pyc"
      - "*/.DS_Store"
      - "*.js"
      - "*/.git/*"
    shell: /bin/bash
    source:
      - $HOME/.bash_profile
    actions:
      test: workon describe2 && nosetests
      run: workon describe2 && ./describe.py

