name: Jeff's MBP
mediator:
  host: localhost #genesis.coralset.com #localhost
  port: 8080 #7331 #8080
projects:
  YACS:
    location: ~/Documents/projects/yacs
    ignore:
      - "*.pyc"
      - "*/.DS_Store"
      - "*/.git/*"
    shell: /bin/bash
    source:
      - $HOME/.bash_profile
    actions:
      test: workon timetable && fab test

  Describe:
    location: ~/Documents/projects/describe
    ignore:
      - "*.pyc"
      - "*/.DS_Store"
      - "*.js"
      - "*/.git/*"
    shell: /bin/bash
    source:
      - $HOME/.bash_profile
    actions:
      test: workon describe2 && nosetests
      run: workon describe2 && ./describe.py

